"""auto_migration

Revision ID: bf18260afbab
Revises: 81bc6c4f99bc
Create Date: 2026-09-16 14:23:08.272404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf18260afbab'
down_revision: Union[str, Sequence[str], None] = '81bc6c4f99bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('yandex_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfile', 'yandex_access_token')
    # ### end Alembic commands ###
