"""auto_migration

Revision ID: c61b5ab387de
Revises: da6af1791696
Create Date: 2026-09-10 12:39:38.631623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61b5ab387de'
down_revision: Union[str, Sequence[str], None] = 'da6af1791696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dish', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Dish', 'UserProfile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Dish', type_='foreignkey')
    op.drop_column('Dish', 'user_id')
    # ### end Alembic commands ###
